name: Release

on:
  release:
    types: [published]

jobs:
  github:
    name: Publish to GitHub releases

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build & upload binaries to release
      uses: taiki-e/upload-rust-binary-action@v1
      with:
        bin: truegrf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  registries:
    name: Publish to NPM / crates.io
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Node toolchain
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Setup cache for Rust
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Install wasm-pack
      run: |
        cargo install wasm-pack

    - name: Update version to the release version
      run: |
        # Remove the "v" from the version.
        VERSION=$(echo ${{ github.ref_name }} | cut -b2-)
        echo "Version: ${VERSION}"

        # Use sed for now, as https://github.com/rust-lang/cargo/issues/7722 isn't in stable yet.
        sed -i 's/version = "0.0.0-git"/version = "'${VERSION}'"/' Cargo.toml
        sed -i 's/version = "0.0.0-git"/version = "'${VERSION}'"/' Cargo.lock

    - name: Create NPM package
      run: |
        wasm-pack build --release --target web
        sed -i 's/"module": "truegrf.js",/"main": "truegrf.js",\n  "type": "module",/' pkg/package.json

    - name: Publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: pkg/package.json
        access: public
        greater-version-only: true

    - name: Publish to crates.io
      run: |
        cargo publish --allow-dirty
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
